name: Deploy release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/shared-public-configs/.github/workflows/publish-public-npm-package.yml@master
    with:
      prepare-script: >-
        cp package.json LICENSE README.md build/ &&
        cd build &&
        tmp=$(mktemp) &&
        jq --arg version "$GITHUB_REF_NAME" '.version = $version' package.json > "$tmp" &&
        mv "$tmp" package.json
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
