name: Validations

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validations:
    uses: croct-tech/github-workflows/.github/workflows/general/javascript-validations.yml@unify-workflows
    with:
      node-version: '16'
      run-tests: false
      run-security: true
      use-private-registry: false
